course = 'mooc-programming-22'
[exercises.part08-01_smallest_average]
id = 151794
checksum = '7b173687bf0adebc4a486a68f6c32031'

[exercises.part08-02_row_sums]
id = 151807
checksum = 'd9973e48318dc29c3327e7897d41ec80'

[exercises.part08-03_list_years]
id = 151795
checksum = '34204b1e729dbe3f9e230ece01aff8bb'

[exercises.part08-04_shopping_list]
id = 151808
checksum = 'ae99378be7d856870fd842230850b805'

[exercises.part08-05_book]
id = 151805
checksum = 'aac905bf98e296530348a26ce1d62953'

[exercises.part08-06_three_classes]
id = 151806
checksum = 'db0a8040524583a0b511483cf1ce31a0'

[exercises.part08-07_pet]
id = 151796
checksum = 'b7a475be3b4f573b0e662c62d56c53db'

[exercises.part08-08_older_book]
id = 151802
checksum = 'ec8edbf83ca00f4ec521f446208bbb97'

[exercises.part08-09_books_of_genre]
id = 151797
checksum = '8a92d4e749d53c617b4e0624f9604e43'

[exercises.part08-10_decreasing_counter]
id = 151799
checksum = 'baa34ecdf760cdde32cc3fbdf5536d12'

[exercises.part08-11_first_and_last_name]
id = 151800
checksum = 'b106215b92f30bfe45dab2b229bc4fa7'

[exercises.part08-12_number_stats]
id = 151801
checksum = '7b15d1eb9de2227eea1a319ac5a9b71b'

[exercises.part08-13_stopwatch]
id = 151804
checksum = '2d59af6633c662644f62bddb79d2a0ce'

[exercises.part08-14_clock]
id = 151803
checksum = '9326d9c6edfc221351a6d919b01f4b54'

[exercises.part08-15_lunchcard]
id = 151809
checksum = 'de1dd39ddb02a80fc5ac43d905a0207f'

[exercises.part08-16_series]
id = 151798
checksum = 'cc7e178145f70ef2440ffcf972d5e79e'
